# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see:
# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Selected version profile. Override with -Pmc_target=<profile>.
mc_target=26.2

# Mod Properties
version=0.0.3-alpha
maven_group=dev.cammo1123
base_name=clickthrough_server
