minecraft_version=26.2
minecraft_supported_versions=26.2
minecraft_dependency_range=[26.2,)

# Fabric
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.0+26.2

# NeoForge
neoforge_version=26.2.0.88
neoforge_dependency_range=[26.2,)
moddevgradle_version=2.0.147

# Quilt
quilt_loader_version=0.30.1

# Enabled Loaders
target_loaders=fabric,neoforge,quilt
