minecraft_version=26.3
minecraft_supported_versions=26.3
minecraft_dependency_range=[26.3,)

# Fabric
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.6+26.3

# NeoForge
neoforge_version=26.3.0.1-beta
neoforge_dependency_range=[26.3,)
moddevgradle_version=2.0.147

# Quilt
quilt_loader_version=0.30.1

# Enabled Loaders
target_loaders=fabric,neoforge,quilt
