modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "clickthrough_server"
version = "${version}"
displayName = "ClickThrough Server"
description = "Click through Signs and Item Frames to Chests and other containers - a server side recreation of ClickThrough+."
authors = "Cameron Youell"

[[dependencies.clickthrough_server]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clickthrough_server]]
modId = "minecraft"
type = "required"
versionRange = "[26.2]"
ordering = "NONE"
side = "BOTH"
